Repository var-bin/RD_FrontEnd_Students_Pack, pull requests merged in 2019-10, with the labels that each got.

#2 Enabled rules for all directories inside repo
  .lintstagedrc
Labels: enhancement, good first issue

#3 Added ability to use classnames with '-'
  .htmllintrc
Labels: enhancement

#4 fix: add missing comma to .htmllintrc
  .htmllintrc
Labels: bug, enhancement
